### ISSUE TITLE
Exception: Invalid device ID

### ISSUE THREAD

**Issue by DieterKoblenz** [ammarzuberi/pyanova#2]
I've copied it from the details page, left anova, the f56-pre part. Tried all variations, still end up with the same error.

**Comment by ammarzuberi** [comment]
What type of Anova device do you have?

**Comment by DieterKoblenz** [comment]
The 2nd generation with bluetooth and wifi

**Comment by lolouk44** [comment]
same issue for me.
What exactly needs to be provided for the ID?
tried the following
`anova f56-a8xxxxx2e8b`
`f56-a8xxxxx2e8b`
`a8xxxxx2e8b`
I have an Anova Precision Cooker Bluetooth & WI-FI 220v UK Plug:
![image](https://user-images.githubusercontent.com/4587746/79557201-11ca2200-809a-11ea-9950-830b8ec53134.png)

```
Traceback (most recent call last):
  File "anova-run.py", line 3, in <module>
    cooker = AnovaCooker('anova f56-a8xxxxx2e8b')
  File "/usr/local/lib/python3.8/site-packages/anova/AnovaCooker.py", line 48, in __init__
    self.update_state()
  File "/usr/local/lib/python3.8/site-packages/anova/AnovaCooker.py", line 53, in update_state
    device_state = self.__get_raw_state()
  File "/usr/local/lib/python3.8/site-packages/anova/AnovaCooker.py", line 87, in __get_raw_state
    raise Exception('Invalid device ID')
Exception: Invalid device ID
```

**Comment by ammarzuberi** [comment]
The differences in models might be causing some issues here. My guess is that the API responds differently depending on the device model. Can you post the response for the following request?

`https://anovaculinary.io/devices/**your_cooker_id_here**/states/?limit=1&max-age=10s`

Feel free to remove the cooker ID from the response.

**Comment by lolouk44** [comment]
Can you confirm the device id format please?
`anova f56-a8xxxxx2e8b`
`f56-a8xxxxx2e8b`
`a8xxxxx2e8b`
so far I don't seem to get any results...

**Comment by lolouk44** [comment]
Using Talend API Tester on Chrome:
![image](https://user-images.githubusercontent.com/4587746/79559180-2fe55180-809d-11ea-8f55-788d2f5b8e73.png)

![image](https://user-images.githubusercontent.com/4587746/79559251-4a1f2f80-809d-11ea-8037-326f2484c045.png)

**Comment by ammarzuberi** [comment]
You have the same app version as me. I have an Anova Pro and my device ID is 22 alphanumeric characters with both upper and lower case letters. I get a JSON response when I make that GET request. What does your device ID look like?

Any chance you'd be willing to share your device ID with me so I can see what's going on? If so, please email it to me. My email address is on my profile.

**Comment by lolouk44** [comment]
Hi @ammarzuberi 
Can you confirm you're received my email?
What are you findings?

Thanks

**Comment by ammarzuberi** [comment]
I received and replied to your email. I'll post back with any findings when I have them.

**Comment by lolouk44** [comment]
Hi @ammarzuberi 
Any luck / findings?

**Comment by hurwitzilan** [comment]
I'm having a similar problem. Happy to send you my deviceID if it will help :)

**Comment by mikeage** [comment]
Same problem, same empty JSON, same format of a device ID (`anova f56-abcdefabcde`). App ersion 3.2.8, model A3, firmware 2.7.7

**Comment by lolouk44** [comment]
To be honest I've given up on this and I'm instead using a [Bluetooth connection](https://github.com/jshridha/anovamaster)

**Comment by stjernstrom** [comment]
I have the same problem, I've been able to communicate with the API with the help of https://github.com/bmedicke/anova.py but the method of getting the ID and secrete feels like a mess and hoped that this should be more stable. 

My first guess was that my account is authenticated with 2FA authentication through google, but I cannot find a way of changing password or changing that :/

**Comment by gj0nyg** [comment]
I fired up mitmproxy to catch the mobile requests that I then put into postman. I had success with https://api.anovaculinary.com/cookers/{{cooker-id}}?secret={{secret}} where cooker-id = anova%20f56-a0xxxxxxa4. It fails if you don't send the secret (http 401)

**Comment by gj0nyg** [comment]
I've found that this library works with my older Wifi/BT Anova https://github.com/bmedicke/anova.py
